In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('cereal.csv')
df.head()

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
0,100% Bran,N,212.12121,12.121212,3.030303,393.93939,30.303030,15.15152,18.181818,3,848.48485,enriched
1,All-Bran,K,212.12121,12.121212,3.030303,787.87879,27.272727,21.21212,15.151515,3,969.69697,enriched
2,All-Bran with Extra Fiber,K,100.00000,8.000000,0.000000,280.00000,28.000000,16.00000,0.000000,3,660.00000,enriched
3,Apple Cinnamon Cheerios,G,146.66667,2.666667,2.666667,240.00000,2.000000,14.00000,13.333333,1,93.33333,enriched
4,Apple Jacks,K,110.00000,2.000000,0.000000,125.00000,1.000000,11.00000,14.000000,2,30.00000,enriched

In [29]:
df.shape

(65, 12)

In [3]:
df['protein'].max()

12.1212121

In [4]:
df['calories'].max()

440.0

In [5]:
df_p= df['calories'].argmax()
df.iloc[df_p]

Name         Grape-Nuts
mfr                   P
calories            440
protein              12
fat                   0
sodium              680
fibre                12
carbo                68
sugars               12
shelf                 3
potassium           360
vitamins       enriched
Name: 30, dtype: object

In [6]:
df_p= df['calories'].argmax()
df.iloc[df_p][0:1]

Name    Grape-Nuts
Name: 30, dtype: object

In [7]:
new_df =df[(df['calories']>400) & (df['protein']>10)]
new_df

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
30,Grape-Nuts,P,440.0,12.0,0.0,680.0,12.0,68.0,12.0,3,360.0,enriched

In [8]:
df['fat'].max()

9.0909091

In [9]:
d_x = df['fat'].argmax()
df.iloc[d_x]

Name         Great Grains Pecan
mfr                           P
calories                363.636
protein                 9.09091
fat                     9.09091
sodium                  227.273
fibre                   9.09091
carbo                   39.3939
sugars                  12.1212
shelf                         3
potassium                303.03
vitamins               enriched
Name: 31, dtype: object

In [10]:
d_x = df['fat'].argmax()
df.iloc[d_x][0:1]

Name    Great Grains Pecan
Name: 31, dtype: object

In [11]:
n_df =df[(df['calories']>100) & (df['protein']>7)&(df['fat']>5) ]
n_df

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
31,Great Grains Pecan,P,363.63636,9.090909,9.090909,227.27273,9.090909,39.39394,12.121212,3,303.0303,enriched

In [12]:
n_df =df[(df['calories']>100) & (df['protein']>7)&(df['fat']>3) ]
n_df

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
0,100% Bran,N,212.12121,12.121212,3.030303,393.93939,30.303030,15.15152,18.181818,3,848.48485,enriched
1,All-Bran,K,212.12121,12.121212,3.030303,787.87879,27.272727,21.21212,15.151515,3,969.69697,enriched
31,Great Grains Pecan,P,363.63636,9.090909,9.090909,227.27273,9.090909,39.39394,12.121212,3,303.03030,enriched

In [13]:
d_y = df['sodium'].max()
d_y

787.87879

In [14]:
d_s = df['sodium'].argmax()
df.iloc[d_s]

Name         All-Bran
mfr                 K
calories      212.121
protein       12.1212
fat            3.0303
sodium        787.879
fibre         27.2727
carbo         21.2121
sugars        15.1515
shelf               3
potassium     969.697
vitamins     enriched
Name: 1, dtype: object

In [15]:
d_s1 = df['sodium'].argmax()
df.iloc[d_s1][0:1]

Name    All-Bran
Name: 1, dtype: object

In [16]:
ns_df =df[(df['calories']>100) & (df['protein']>7)&(df['fat']>3)&(df['sodium']>500) ]
ns_df

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
1,All-Bran,K,212.12121,12.121212,3.030303,787.87879,27.272727,21.21212,15.151515,3,969.69697,enriched

In [17]:
d_f = df['fibre'].max()
d_f

30.30303

In [18]:
d_s1 = df['fibre'].argmax()
df.iloc[d_s1][0:1]

Name    100% Bran
Name: 0, dtype: object

In [19]:
d_s = df['fibre'].argmax()
df.iloc[d_s]

Name         100% Bran
mfr                  N
calories       212.121
protein        12.1212
fat             3.0303
sodium         393.939
fibre           30.303
carbo          15.1515
sugars         18.1818
shelf                3
potassium      848.485
vitamins      enriched
Name: 0, dtype: object

In [20]:
ns_d_f =df[(df['calories']>100) & (df['protein']>7)&(df['fat']>3)&(df['sodium']>500)&(df['fibre']>20) ]
ns_d_f

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
1,All-Bran,K,212.12121,12.121212,3.030303,787.87879,27.272727,21.21212,15.151515,3,969.69697,enriched

In [21]:
d_f = df['carbo'].max()
d_f

68.0

In [22]:
d_c = df['carbo'].argmax()
df.iloc[d_c][0:1]

Name    Grape-Nuts
Name: 30, dtype: object

In [23]:
df[df['vitamins']=="enriched"]

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
0,100% Bran,N,212.12121,12.121212,3.030303,393.93939,30.303030,15.15152,18.181818,3,848.48485,enriched
1,All-Bran,K,212.12121,12.121212,3.030303,787.87879,27.272727,21.21212,15.151515,3,969.69697,enriched
2,All-Bran with Extra Fiber,K,100.00000,8.000000,0.000000,280.00000,28.000000,16.00000,0.000000,3,660.00000,enriched
3,Apple Cinnamon Cheerios,G,146.66667,2.666667,2.666667,240.00000,2.000000,14.00000,13.333333,1,93.33333,enriched
4,Apple Jacks,K,110.00000,2.000000,0.000000,125.00000,1.000000,11.00000,14.000000,2,30.00000,enriched
5,Basic 4,G,173.33333,4.000000,2.666667,280.00000,2.666667,24.00000,10.666667,3,133.33333,enriched
6,Bran Chex,R,134.32836,2.985075,1.492537,298.50746,5.970149,22.38806,8.955224,1,186.56716,enriched
7,Bran Flakes,P,134.32836,4.477612,0.000000,313.43284,7.462687,19.40299,7.462687,3,283.58209,enriched
8,Cap'n'Crunch,Q,160.00000,1.333333,2.666667,293.33333,0.000000,16.00000,16.000000,2,46.66667,enriched
9,Cheerios,G,88.00000,4.800000,1.600000,232.00000,1.600000,13.60000,0.800000,1,84.00000,enriched
10,Cinnamon Toast Crunch,G,160.00000,1.333333,4.000000,280.00000,0.000000,17.33333,12.000000,2,60.00000,enriched
11,Clusters,G,220.00000,6.000000,4.000000,280.00000,4.000000,26.00000,14.000000,3,210.00000,enriched
12,Cocoa Puffs,G,110.00000,1.000000,1.000000,180.00000,0.000000,12.00000,13.000000,2,55.00000,enriched
13,Corn Chex,R,110.00000,2.000000,0.000000,280.00000,0.000000,22.00000,3.000000,1,25.00000,enriched
14,Corn Flakes,K,100.00000,2.000000,0.000000,290.00000,1.000000,21.00000,2.000000,1,35.00000,enriched
15,Corn Pops,K,110.00000,1.000000,0.000000,90.00000,1.000000,13.00000,12.000000,2,20.00000,enriched
16,Count Chocula,G,110.00000,1.000000,1.000000,180.00000,0.000000,12.00000,13.000000,2,65.00000,enriched
17,Cracklin' Oat Bran,K,220.00000,6.000000,6.000000,280.00000,8.000000,20.00000,14.000000,3,320.00000,enriched
18,Crispix,K,110.00000,2.000000,0.000000,220.00000,1.000000,21.00000,3.000000,3,30.00000,enriched
19,Crispy Wheat & Raisins,G,133.33333,2.666667,1.333333,186.66667,2.666667,14.66667,13.333333,3,160.00000,enriched
20,Double Chex,R,133.33333,2.666667,0.000000,253.33333,1.333333,24.00000,6.666667,3,106.66667,enriched
21,Froot Loops,K,110.00000,2.000000,1.000000,125.00000,1.000000,11.00000,13.000000,2,30.00000,enriched
22,Frosted Flakes,K,146.66667,1.333333,0.000000,266.66667,1.333333,18.66667,14.666667,1,33.33333,enriched
23,Frosted Mini-Wheats,K,125.00000,3.750000,0.000000,0.00000,3.750000,17.50000,8.750000,2,125.00000,enriched
24,Fruit & Fibre: Dates Walnuts and Oats,P,179.10448,4.477612,2.985075,238.80597,7.462687,17.91045,14.925373,3,298.50746,enriched
25,Fruitful Bran,K,179.10448,4.477612,0.000000,358.20896,7.462687,20.89552,17.910448,3,283.58209,enriched
26,Fruity Pebbles,P,146.66667,1.333333,1.333333,180.00000,0.000000,17.33333,16.000000,2,33.33333,enriched
27,Golden Crisp,P,113.63636,2.272727,0.000000,51.13636,0.000000,12.50000,17.045455,1,45.45455,enriched
28,Golden Grahams,G,146.66667,1.333333,1.333333,373.33333,0.000000,20.00000,12.000000,2,60.00000,enriched
29,Grape Nuts Flakes,P,113.63636,3.409091,1.136364,159.09091,3.409091,17.04545,5.681818,3,96.59091,enriched
30,Grape-Nuts,P,440.00000,12.000000,0.000000,680.00000,12.000000,68.00000,12.000000,3,360.00000,enriched
31,Great Grains Pecan,P,363.63636,9.090909,9.090909,227.27273,9.090909,39.39394,12.121212,3,303.03030,enriched
32,Honey Graham Ohs,Q,120.00000,1.000000,2.000000,220.00000,1.000000,12.00000,11.000000,2,45.00000,enriched
33,Honey Nut Cheerios,G,146.66667,4.000000,1.333333,333.33333,2.000000,15.33333,13.333333,1,120.00000,enriched
34,Honey-comb,P,82.70677,0.751880,0.000000,135.33835,0.000000,10.52632,8.270677,1,26.31579,enriched
36,Kix,G,73.33333,1.333333,0.666667,173.33333,0.000000,14.00000,2.000000,2,26.66667,enriched
37,Life,Q,149.25373,5.970149,2.985075,223.88060,2.985075,17.91045,8.955224,2,141.79104,enriched
38,Lucky Charms,G,110.00000,2.000000,1.000000,180.00000,0.000000,12.00000,12.000000,2,55.00000,enriched
39,Mueslix Crispy Blend,K,238.80597,4.477612,2.985075,223.88060,4.477612,25.37313,19.402985,3,238.80597,enriched
40,Multi-Grain Cheerios,G,100.00000,2.000000,1.000000,220.00000,2.000000,15.00000,6.000000,1,90.00000,enriched
41,Nut&Honey Crunch,K,179.10448,2.985075,1.492537,283.58209,0.000000,22.38806,13.432836,2,59.70149,enriched
42,Nutri-Grain Almond-Raisin,K,208.95522,4.477612,2.985075,328.35821,4.477612,31.34328,10.447761,3,194.02985,enriched
43,Oatmeal Raisin Crisp,G,260.00000,6.000000,4.000000,340.00000,3.000000,27.00000,20.000000,3,240.00000,enriched
44,Post Nat. Raisin Bran,P,179.10448,4.477612,1.492537,298.50746,8.955224,16.41791,20.895522,3,388.05970,enriched
47,Quaker Oat Squares,Q,200.00000,8.000000,2.000000,270.00000,4.000000,28.00000,12.000000,3,220.00000,enriched
48,Raisin Bran,K,160.00000,4.000000,1.333333,280.00000,6.666667,18.66667,16.000000,2,320.00000,enriched
49,Raisin Nut Bran,G,200.00000,6.000000,4.000000,280.00000,5.000000,21.00000,16.000000,3,280.00000,enriched
50,Raisin Squares,K,180.00000,4.000000,0.000000,0.00000,4.000000,30.00000,12.000000,3,220.00000,enriched
51,Rice Chex,R,97.34513,0.884956,0.000000,212.38938,0.000000,20.35398,1.769912,1,26.54867,enriched
52,Rice Krispies,K,110.00000,2.000000,0.000000,290.00000,0.000000,22.00000,3.000000,1,35.00000,enriched
55,Smacks,K,146.66667,2.666667,1.333333,93.33333,1.333333,12.00000,20.000000,2,53.33333,enriched
56,Special K,K,110.00000,6.000000,0.000000,230.00000,1.000000,16.00000,3.000000,1,55.00000,enriched
60,Triples,G,146.66667,2.666667,1.333333,333.33333,0.000000,28.00000,4.000000,3,80.00000,enriched
61,Trix,G,110.00000,1.000000,1.000000,140.00000,0.000000,13.00000,12.000000,2,25.00000,enriched
62,Wheat Chex,R,149.25373,4.477612,1.492537,343.28358,4.477612,25.37313,4.477612,1,171.64179,enriched
63,Wheaties,G,100.00000,3.000000,1.000000,200.00000,3.000000,17.00000,3.000000,1,110.00000,enriched
64,Wheaties Honey Gold,G,146.66667,2.666667,1.333333,266.66667,1.333333,21.33333,10.666667,1,80.00000,enriched

In [28]:
df[df['vitamins']=="none"]

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
46,Puffed Rice,Q,50.00000,1.000000,0.0,0.0,0.000000,13.00000,0.0,3,15.00000,none
53,Shredded Wheat 'n'Bran,N,134.32836,4.477612,0.0,0.0,5.970149,28.35821,0.0,1,208.95522,none
54,Shredded Wheat spoon size,N,134.32836,4.477612,0.0,0.0,4.477612,29.85075,0.0,1,179.10448,none

In [32]:
df[df['vitamins']=="100%"]

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
35,Just Right Fruit & Nut,K,186.66667,4.0,1.333333,226.66667,2.666667,26.66667,12.0,3,126.66667,100%
45,Product 19,K,100.00000,3.0,0.000000,320.00000,1.000000,20.00000,3.0,3,45.00000,100%
57,Total Corn Flakes,G,110.00000,2.0,1.000000,200.00000,0.000000,21.00000,3.0,3,35.00000,100%
58,Total Raisin Bran,G,140.00000,3.0,1.000000,190.00000,4.000000,15.00000,14.0,3,230.00000,100%
59,Total Whole Grain,G,100.00000,3.0,1.000000,200.00000,3.000000,16.00000,3.0,3,110.00000,100%

In [31]:
df[df['shelf']>2]

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
0,100% Bran,N,212.12121,12.121212,3.030303,393.93939,30.303030,15.15152,18.181818,3,848.48485,enriched
1,All-Bran,K,212.12121,12.121212,3.030303,787.87879,27.272727,21.21212,15.151515,3,969.69697,enriched
2,All-Bran with Extra Fiber,K,100.00000,8.000000,0.000000,280.00000,28.000000,16.00000,0.000000,3,660.00000,enriched
5,Basic 4,G,173.33333,4.000000,2.666667,280.00000,2.666667,24.00000,10.666667,3,133.33333,enriched
7,Bran Flakes,P,134.32836,4.477612,0.000000,313.43284,7.462687,19.40299,7.462687,3,283.58209,enriched
11,Clusters,G,220.00000,6.000000,4.000000,280.00000,4.000000,26.00000,14.000000,3,210.00000,enriched
17,Cracklin' Oat Bran,K,220.00000,6.000000,6.000000,280.00000,8.000000,20.00000,14.000000,3,320.00000,enriched
18,Crispix,K,110.00000,2.000000,0.000000,220.00000,1.000000,21.00000,3.000000,3,30.00000,enriched
19,Crispy Wheat & Raisins,G,133.33333,2.666667,1.333333,186.66667,2.666667,14.66667,13.333333,3,160.00000,enriched
20,Double Chex,R,133.33333,2.666667,0.000000,253.33333,1.333333,24.00000,6.666667,3,106.66667,enriched
24,Fruit & Fibre: Dates Walnuts and Oats,P,179.10448,4.477612,2.985075,238.80597,7.462687,17.91045,14.925373,3,298.50746,enriched
25,Fruitful Bran,K,179.10448,4.477612,0.000000,358.20896,7.462687,20.89552,17.910448,3,283.58209,enriched
29,Grape Nuts Flakes,P,113.63636,3.409091,1.136364,159.09091,3.409091,17.04545,5.681818,3,96.59091,enriched
30,Grape-Nuts,P,440.00000,12.000000,0.000000,680.00000,12.000000,68.00000,12.000000,3,360.00000,enriched
31,Great Grains Pecan,P,363.63636,9.090909,9.090909,227.27273,9.090909,39.39394,12.121212,3,303.03030,enriched
35,Just Right Fruit & Nut,K,186.66667,4.000000,1.333333,226.66667,2.666667,26.66667,12.000000,3,126.66667,100%
39,Mueslix Crispy Blend,K,238.80597,4.477612,2.985075,223.88060,4.477612,25.37313,19.402985,3,238.80597,enriched
42,Nutri-Grain Almond-Raisin,K,208.95522,4.477612,2.985075,328.35821,4.477612,31.34328,10.447761,3,194.02985,enriched
43,Oatmeal Raisin Crisp,G,260.00000,6.000000,4.000000,340.00000,3.000000,27.00000,20.000000,3,240.00000,enriched
44,Post Nat. Raisin Bran,P,179.10448,4.477612,1.492537,298.50746,8.955224,16.41791,20.895522,3,388.05970,enriched
45,Product 19,K,100.00000,3.000000,0.000000,320.00000,1.000000,20.00000,3.000000,3,45.00000,100%
46,Puffed Rice,Q,50.00000,1.000000,0.000000,0.00000,0.000000,13.00000,0.000000,3,15.00000,none
47,Quaker Oat Squares,Q,200.00000,8.000000,2.000000,270.00000,4.000000,28.00000,12.000000,3,220.00000,enriched
49,Raisin Nut Bran,G,200.00000,6.000000,4.000000,280.00000,5.000000,21.00000,16.000000,3,280.00000,enriched
50,Raisin Squares,K,180.00000,4.000000,0.000000,0.00000,4.000000,30.00000,12.000000,3,220.00000,enriched
57,Total Corn Flakes,G,110.00000,2.000000,1.000000,200.00000,0.000000,21.00000,3.000000,3,35.00000,100%
58,Total Raisin Bran,G,140.00000,3.000000,1.000000,190.00000,4.000000,15.00000,14.000000,3,230.00000,100%
59,Total Whole Grain,G,100.00000,3.000000,1.000000,200.00000,3.000000,16.00000,3.000000,3,110.00000,100%
60,Triples,G,146.66667,2.666667,1.333333,333.33333,0.000000,28.00000,4.000000,3,80.00000,enriched

In [34]:
df[df['shelf']<3]

,Name,mfr,calories,protein,fat,sodium,fibre,carbo,sugars,shelf,potassium,vitamins
3,Apple Cinnamon Cheerios,G,146.66667,2.666667,2.666667,240.00000,2.000000,14.00000,13.333333,1,93.33333,enriched
4,Apple Jacks,K,110.00000,2.000000,0.000000,125.00000,1.000000,11.00000,14.000000,2,30.00000,enriched
6,Bran Chex,R,134.32836,2.985075,1.492537,298.50746,5.970149,22.38806,8.955224,1,186.56716,enriched
8,Cap'n'Crunch,Q,160.00000,1.333333,2.666667,293.33333,0.000000,16.00000,16.000000,2,46.66667,enriched
9,Cheerios,G,88.00000,4.800000,1.600000,232.00000,1.600000,13.60000,0.800000,1,84.00000,enriched
10,Cinnamon Toast Crunch,G,160.00000,1.333333,4.000000,280.00000,0.000000,17.33333,12.000000,2,60.00000,enriched
12,Cocoa Puffs,G,110.00000,1.000000,1.000000,180.00000,0.000000,12.00000,13.000000,2,55.00000,enriched
13,Corn Chex,R,110.00000,2.000000,0.000000,280.00000,0.000000,22.00000,3.000000,1,25.00000,enriched
14,Corn Flakes,K,100.00000,2.000000,0.000000,290.00000,1.000000,21.00000,2.000000,1,35.00000,enriched
15,Corn Pops,K,110.00000,1.000000,0.000000,90.00000,1.000000,13.00000,12.000000,2,20.00000,enriched
16,Count Chocula,G,110.00000,1.000000,1.000000,180.00000,0.000000,12.00000,13.000000,2,65.00000,enriched
21,Froot Loops,K,110.00000,2.000000,1.000000,125.00000,1.000000,11.00000,13.000000,2,30.00000,enriched
22,Frosted Flakes,K,146.66667,1.333333,0.000000,266.66667,1.333333,18.66667,14.666667,1,33.33333,enriched
23,Frosted Mini-Wheats,K,125.00000,3.750000,0.000000,0.00000,3.750000,17.50000,8.750000,2,125.00000,enriched
26,Fruity Pebbles,P,146.66667,1.333333,1.333333,180.00000,0.000000,17.33333,16.000000,2,33.33333,enriched
27,Golden Crisp,P,113.63636,2.272727,0.000000,51.13636,0.000000,12.50000,17.045455,1,45.45455,enriched
28,Golden Grahams,G,146.66667,1.333333,1.333333,373.33333,0.000000,20.00000,12.000000,2,60.00000,enriched
32,Honey Graham Ohs,Q,120.00000,1.000000,2.000000,220.00000,1.000000,12.00000,11.000000,2,45.00000,enriched
33,Honey Nut Cheerios,G,146.66667,4.000000,1.333333,333.33333,2.000000,15.33333,13.333333,1,120.00000,enriched
34,Honey-comb,P,82.70677,0.751880,0.000000,135.33835,0.000000,10.52632,8.270677,1,26.31579,enriched
36,Kix,G,73.33333,1.333333,0.666667,173.33333,0.000000,14.00000,2.000000,2,26.66667,enriched
37,Life,Q,149.25373,5.970149,2.985075,223.88060,2.985075,17.91045,8.955224,2,141.79104,enriched
38,Lucky Charms,G,110.00000,2.000000,1.000000,180.00000,0.000000,12.00000,12.000000,2,55.00000,enriched
40,Multi-Grain Cheerios,G,100.00000,2.000000,1.000000,220.00000,2.000000,15.00000,6.000000,1,90.00000,enriched
41,Nut&Honey Crunch,K,179.10448,2.985075,1.492537,283.58209,0.000000,22.38806,13.432836,2,59.70149,enriched
48,Raisin Bran,K,160.00000,4.000000,1.333333,280.00000,6.666667,18.66667,16.000000,2,320.00000,enriched
51,Rice Chex,R,97.34513,0.884956,0.000000,212.38938,0.000000,20.35398,1.769912,1,26.54867,enriched
52,Rice Krispies,K,110.00000,2.000000,0.000000,290.00000,0.000000,22.00000,3.000000,1,35.00000,enriched
53,Shredded Wheat 'n'Bran,N,134.32836,4.477612,0.000000,0.00000,5.970149,28.35821,0.000000,1,208.95522,none
54,Shredded Wheat spoon size,N,134.32836,4.477612,0.000000,0.00000,4.477612,29.85075,0.000000,1,179.10448,none
55,Smacks,K,146.66667,2.666667,1.333333,93.33333,1.333333,12.00000,20.000000,2,53.33333,enriched
56,Special K,K,110.00000,6.000000,0.000000,230.00000,1.000000,16.00000,3.000000,1,55.00000,enriched
61,Trix,G,110.00000,1.000000,1.000000,140.00000,0.000000,13.00000,12.000000,2,25.00000,enriched
62,Wheat Chex,R,149.25373,4.477612,1.492537,343.28358,4.477612,25.37313,4.477612,1,171.64179,enriched
63,Wheaties,G,100.00000,3.000000,1.000000,200.00000,3.000000,17.00000,3.000000,1,110.00000,enriched
64,Wheaties Honey Gold,G,146.66667,2.666667,1.333333,266.66667,1.333333,21.33333,10.666667,1,80.00000,enriched

In [36]:
d_f_s = df['sugars'].min()
d_f_s

0.0

In [37]:
d_f_s1 = df['sugars'].argmin()
df.iloc[d_f_s1][0:1]

Name    All-Bran with Extra Fiber
Name: 2, dtype: object

In [38]:
d_f_s1 = df['sugars'].argmin()
df.iloc[d_f_s1]

Name         All-Bran with Extra Fiber
mfr                                  K
calories                           100
protein                              8
fat                                  0
sodium                             280
fibre                               28
carbo                               16
sugars                               0
shelf                                3
potassium                          660
vitamins                      enriched
Name: 2, dtype: object